# Generated by Django 3.1.2 on 2021-04-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20, unique=True)),
                ('LastName', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Password', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
