# Generated by Django 3.1.2 on 2021-05-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
